backend:
    name: git-gateway
    branch: master
  
media_folder: static/img
public_folder: /src/images
site_url: https://byronwade.com
display_url: https://byronwade.com
logo_url: https://www.byronwade.com/icons/icon-48x48.png
publish_mode: editorial_workflow

collections:
  - label: "Blog"
    name: "blog"
    preview_path: "blog/{{year}}/{{month}}/{{slug}}/"
    folder: "_posts/"
    create: true
    update: true
    delete: true
    filter:
      - field: "categories"
        value: "business"
    fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Author", name: "auther", widget: "string", default: "Byron Wade"}
        - {label: "Publish Date", name: "date", widget: "datetime"}
        - {label: "Thumbnail", name: "thumbnail", widget: "image"}
        - {label: "Featured Image", name: "features-image", widget: "image"}
        - {label: "Body", name: "body", widget: "markdown"}
  - label: "Projects"
    name: "projects"
    preview_path: "projects/{{year}}/{{month}}/{{slug}}/"
    folder: "_projects/"
    create: true
    update: true
    delete: true
    filter:
      - field: "categories"
        value: "business"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Website Deploy Location", name: "deploy", widget: "string"}
      - {label: "Github Location", name: "github", widget: "string", required: false}
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: ["React"]
      - label: "Type"
        name: "website-app-type"
        widget: "select"
        options:
            - { label: "Website", value: "Website" }
            - { label: "Web Application", value: "Web Application" }
            - { label: "Mobile App", value: "Mobile App" }
            - { label: "Website & Web Application", value: "Website & Web Application" }
            - { label: "Website & Web Application & Mobile App", value: "Website & Web Application & Mobile App" }
            
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Featured Image", name: "projects-features-image", widget: "image"}
      - label: "Any other images"
        name: "all-other-images"
        widget: "image"
        media_library:
            config:
              multiple: true