backend:
    name: github
    branch: master
    repo: byronwade/Websites
    use_graphql: true
  
media_folder: static/img
public_folder: /src/images
site_url: https://byronwade.com
display_url: https://byronwade.com
logo_url: https://www.byronwade.com/icons/icon-48x48.png
publish_mode: editorial_workflow

collections:
  - label: "Blog"
    name: "blog"
    preview_path: "blog/{{year}}-{{month}}-{{day}}-{{slug}}"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    folder: "blog/"
    path: 'blog/{{year}}/{{slug}}'
    create: true
    update: true
    delete: true
    filter:
      - field: "categories"
        value: "business"
    fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Author", name: "auther", widget: "string", default: "Byron Wade"}
        - {label: "Publish Date", name: "date", widget: "datetime"}
        - {label: "Thumbnail", name: "thumbnail", widget: "image"}
        - {label: "Featured Image", name: "features-image", widget: "image"}
        - {label: "Body", name: "body", widget: "markdown"}
  - label: "Portfolio"
    name: "portfolio"
    preview_path: "portfolio/{{year}}-{{month}}-{{day}}-{{slug}}"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    folder: "portfolio/"
    path: 'portfolio/{{year}}/{{slug}}'
    create: true
    update: true
    delete: true
    filter:
      - field: "categories"
        value: "business" 
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Website Deploy Location", name: "deploy", widget: "string"}
      - {label: "Github Location", name: "github", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Featured Image", name: "projects-features-image", widget: "image"}